### ISSUE TITLE
Where to find enwiki.tok.txt?

### ISSUE THREAD

**Issue by sedrickkeh** [cindyxinyiwang/expand-via-lexicon-based-adaptation#1]
In the file `src/make_pseudo_mono.py`, there is the line `src_file = "data/enwiki.tok.txt"`. Could you point to where I can access this dataset?

Thank you!

**Comment by cindyxinyiwang** [comment]
Hey,

This is a subsampled English wikipedia data, processed and tokenized using [Stanza](https://stanfordnlp.github.io/stanza/tokenize.html). You can prepare the data you want to augment into the low-resource languages yourself. I also uploaded the data files I used and you can download it following the instructions in [README](https://github.com/cindyxinyiwang/expand-via-lexicon-based-adaptation#download-prepared-data)
